### PR TITLE
sample code to use identity in the application

### PR DESCRIPTION
**Pull request by ahmetkocadogan**
I added sample code to access identity and user details in code, created a page "UserDetails" for samples.

This may help people to get started with the template faster.

Thank you again for the help @ArgoZhang

### CODE REVIEW

**Comment by ArgoZhang** [comment]
@ahmetkocadogan hi bro. I had a code review. some code is not perfect. I will make it better later

**Comment by ahmetkocadogan** [comment]
@ArgoZhang  yeah, first issue i can say is, after login, when i try to navigate a page that does not exists, site redirects me to login page. needs some work :)

**Comment by ArgoZhang** [comment]
@ahmetkocadogan  I push a commit to refactor the code. remove the HttpContext

**Comment by ahmetkocadogan** [comment]
@ArgoZhang wow much better now with authenticatonstateprovider. 

How can we get rid of redirecting to  login page when we try to navigate a non-valid url like /userssss? We should see 'there is nothing in this address' instead of login page. Maybe we need an auth state check in the `<Redirect/>` component.

**Comment by ArgoZhang** [comment]
@ahmetkocadogan I had added the NotFoundLayout in this project. You can try it again

**Pull request merged**
